// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Question struct {
	ID          int32 `json:"id"`
	LanguageID  int32 `json:"language_id"`
	Topic       string `json:"topic"`
	Question    string `json:"question"`
	ChoiceA     string `json:"choice_a"`
	ChoiceB     string `json:"choice_b"`
	ChoiceC     string `json:"choice_c"`
	ChoiceD     string `json:"choice_d"`
	Answer      string `json:"answer"`
	Explanation sql.NullString  `json:"explanation"`
	QuestionCode sql.NullString `json:"question_code"`
	Code 		sql.NullString `json:"code"`
	UserAnswer  string `json:"user_answer"`
	UserChoice  string `json:"user_choice"`
}

type Language struct {
	ID          int32 `json:"id"`
	Name        string `json:"name"`
	Logo		string `json:"logo"`
	Width		int32 `json:"width"`
	AceMode	string `db:"ace_mode" json:"ace_mode"`
	Active		bool `json:"active" db:"active"`
}